### ISSUE TITLE
./gradlew runClient: java.lang.NullPointerException at net.minecraftforge.fml.common.network.NetworkRegistry.newChannel(NetworkRegistry.java:207)

### ISSUE THREAD

**Issue by les-citrons** [quat1024/modern-forge-1.12-template#2]
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Forge Mod Loader (FML)
	Caused by: java.lang.NullPointerException
			at net.minecraftforge.fml.common.network.NetworkRegistry.newChannel(NetworkRegistry.java:207)
			at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.registerChannel(FMLNetworkHandler.java:185)
			at net.minecraftforge.fml.common.FMLContainer.modConstruction(FMLContainer.java:92)
			at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
			at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
			at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
			at java.lang.reflect.Method.invoke(Method.java:498)
			at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
			at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
			at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
			at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
			at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
			at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
			at com.google.common.eventbus.EventBus.post(EventBus.java:217)
			at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
			at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
			at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
			at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
			at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
			at java.lang.reflect.Method.invoke(Method.java:498)
			at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
			at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
			at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
			at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
			at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
			at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
			at com.google.common.eventbus.EventBus.post(EventBus.java:217)
			at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
			at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:595)
			at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
			at net.minecraft.client.Minecraft.init(Minecraft.java:467)
			at net.minecraft.client.Minecraft.run(Minecraft.java:378)
			at net.minecraft.client.main.Main.main(Main.java:123)
			at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
			at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
			at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
			at java.lang.reflect.Method.invoke(Method.java:498)
			at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
			at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
			at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
			at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
			at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
			at java.lang.reflect.Method.invoke(Method.java:498)
			at net.minecraftforge.legacydev.Main.start(Main.java:86)
			at net.minecraftforge.legacydev.MainClient.main(MainClient.java:29)

I got this error with the forge-provided MDK as well.

**Comment by Incandescent-Turtle** [comment]
I am also getting this exception.

I am just cloning this repo and trying to build and run it as-is and no dice

**Comment by mica-alex** [comment]
Same issue here

**Comment by quat1024** [comment]
Odd, maybe something in Forge broke. I'll look into this after i get settled with uni

**Comment by mica-alex** [comment]
This is currently holding me back from proper development on two of my current mods, so I am also looking into the issue. If I figure it out, I will let you know. This does not appear to be specific to this repo though, as it's been posted a few times through out the years: https://github.com/MinecraftForge/ForgeGradle/issues/748

Edit: This is also relevant, but I have not been able to resolve using the suggestions: https://stackoverflow.com/questions/68377027/minecraft-forge-mod-loader-fml-loading-and-crashing-mc

Edit: More relevant information: https://github.com/MinecraftForge/ForgeGradle/issues/750

**Comment by opakii** [comment]
Bump, I'm also getting this exception.

**Comment by Gat0Dev** [comment]
bump...

**Comment by opakii** [comment]
bump

**Comment by ph1823** [comment]
Same issue her try to delee gradle cache, no work, follow the link of @mica-alex no work :/ have you a solution to fix this error ? thank !

**Comment by GatoDev** [comment]
I don't know why repo owner is deleting the comments…

I must say that this type of errors still happen to me, but now Minecraft initializes anyway. Before was not letting start it. But now yes, I don't know why TBH.

**Comment by quat1024** [comment]
Because your comments are worthless and just say "bump"

**Comment by quat1024** [comment]
This is just a template repo, guys. I did not write ForgeGradle, I do not maintain ForgeGradle, and I have no idea how it works. Instead of sending me daily "bump" emails, you could try doing your own debugging. You're going to be starting from the same position I was starting from because again, I did not write ForgeGradle.

**Comment by ph1823** [comment]
> I don't know why repo owner is deleting the comments…
> 
> I must say that this type of errors still happen to me, but now Minecraft initializes anyway. Before was not letting start it. But now yes, I don't know why TBH.

For me that dont start and my error is appeared before install mixin on a project mods si i try to demo/template project and still dont work :(

> This is just a template repo, guys. I did not write ForgeGradle, I do not maintain ForgeGradle, and I have no idea how it works. Instead of sending me daily "bump" emails, you could try doing your own debugging. You're going to be starting from the same position I was starting from because again, I did not write ForgeGradle.

You can unsubscribe to this issue no ?
I understand that it is frustrating to receive emails about a bug that you are not the author of, but it is also frustrating for us to have this bug and for testing our mods to have to go to another PC or the  build, because yes on another PC my runClient works and when I test my mods on the Minecraft launcher it works too.

You can closed this issue if you want and as well as prohibit future comments if you really want to stop receiving emails.

**Comment by ph1823** [comment]
For everyone has this problme, i have found a solution for me.
By asking the Minecraft Forge France community, they redirected me to several posts and recommended that I download the project sources, it worked.

You can follow this: https://www.jetbrains.com/idea/whatsnew/#page__content-build-tools to download the sources or click on the "download" icon on your gradle project.

Hope it works for you too.

**Comment by christiaan20** [comment]
> For everyone has this problme, i have found a solution for me. By asking the Minecraft Forge France community, they redirected me to several posts and recommended that I download the project sources, it worked.
> 
> You can follow this: https://www.jetbrains.com/idea/whatsnew/#page__content-build-tools to download the sources or click on the "download" icon on your gradle project.
> 
> Hope it works for you too.

While your proposed solution here didn't work for me. It did give me the idea that maybe this new feature of intellij 2023 is the issue and low and behold downgrading to a good old intellij 2021 fixed this issue for me, thx for the inspiration!

**Comment by GatoDev** [comment]
Thanks you all guys for sharing your solutions. If this happens again to me I will check them all.

**Comment by makkarpov** [comment]
The root cause is that ASM library is included in dependencies twice: 5.2 and 6.2, which could be confirmed by `./gradlew dependencies` task:

```
+--- net.minecraftforge:mergetool:1.0.13
|    +--- org.ow2.asm:asm:6.2

<skipped>

```

**Comment by quat1024** [comment]
I've finally actually reproduced this on one of my machines :/

Still don't know what's going on

**Comment by Fred-Redstone-2** [comment]
Update to that: if I redownload the Gradle files using the download button, everything worked... is to say that the game runs, but there's an exception that doesn't crash the game.

**Comment by KisaragiEffective** [comment]
Hi, I am running into same issues. I broke down issue into a root cause, which is simple:

```java
package net.minecraftforge.fml.relauncher;

public enum Side {
    CLIENT,
    SERVER,
    BUKKIT; // <-- ???

    public boolean isServer() {
        return !this.isClient();
    }

    public boolean isClient() {
        return this == CLIENT;
    }
}
```

How it'd be as above?? I don't have an idea.

**Comment by floorence** [comment]
> Update to that: if I redownload the Gradle files using the download button, everything worked... is to say that the game runs, but there's an exception that doesn't crash the game.

Same here... for me it even "works" if I use the default build.gradle and gradle-wrapper.properties (Gradle 4.9 and ForgeGradle 3.x) as the default 1.12.2 mdk, as long as you press the Gradle "Download Sources" button. An IllegalArgumentException is thrown but the game doesn't crash.

**Comment by xzhao4545** [comment]
I've found a solution, directly create an enum in the project directory: net.minecraftforge.fml.relauncher.Side, to overwrite the original Side enum.
```Java
package net.minecraftforge.fml.relauncher;

public enum Side {
    CLIENT,
    SERVER;

    private Side() {
    }

    public boolean isServer() {
        return !this.isClient();
    }

    public boolean isClient() {
        return this == CLIENT;
    }
}
```

**Comment by tgstyle** [comment]
It can also be fixed with a mixin, code here -

https://github.com/tgstyle/MCT-Immersive-Technology/tree/1.12.2-1.10-Dev

https://github.com/tgstyle/MCT-Immersive-Technology/blob/1.12.2-1.10-Dev/src/main/java/mctmods/immersivetechnology/mixin/MixinMCTNetworkRegistry.java

**Comment by KisaragiEffective** [comment]
Note: the above code is governed by GPL v3, which implies including it on to this template or your code base would be inappropriate unless you are going to change license (or you have picked it - whatever)

**Comment by crafter312** [comment]
I also had `java.lang.IllegalArgumentException` and `java.lang.NullPointerException`, which supposedly is the same as this issue report here. After some tinkering, I was able to fix the `java.lang.IllegalArgumentException` error by adding the following block to the `dependencies` section of `build.gradle`:

```
configurations.all {
	resolutionStrategy {
		// Force the main Forge artifacts to use the known compatible ASM 5.0.3 version
		eachDependency { DependencyResolveDetails details ->
			if (details.requested.group == 'org.ow2.asm' && details.requested.name != 'asm-all') {
				// Check if the requested version is higher than 5.2 (i.e., the problem versions like 6.2)
				if (details.requested.version.toFloat() > 5.2f) {
					details.useVersion '5.0.3'
				}
			}
		}
	}
}
```

I have no idea if this is relevant to this issue report or not, I'm just assuming it is based on the fact that someone marked #3  as a duplicate of this one.

All that's left now for me now is the `NullPointerException`. I've tried a bunch of random things to fix it, but have had no luck so far.

**Comment by WinDanesz** [comment]
This is my usual fix for this NPE in Intellij, works ok with latest IJ too. The Gradle tab's Download Sources button

![Image](https://github.com/user-attachments/assets/576b9f7c-ac34-4c3e-a498-f6ed4e950053)

**Comment by Yi-Jian-Zai-Tian-Ya** [comment]
> 这是我在Intellij中处理NPE的常用方法，最新IJ也能正常使用。Gradle标签页的下载资源按钮
> 
> ![Image](https://github.com/user-attachments/assets/576b9f7c-ac34-4c3e-a498-f6ed4e950053)

太厉害了Bro，我之前误删了~/.gradle文件夹下相关的依赖文件，无法运行客户端的问题已经困扰我四五天了，这个方法真的有用，非常感谢
